### ISSUE TITLE
Job queues with custom prefix could not be discovered

### ISSUE THREAD

**Issue by ccw** [mixmaxhq/arena#14]
The prefix of the job queue in bull is customizable according to the [reference doc](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue). But, with customized prefix,  those queues wouldn't be able to be listed in arena queues overview page. Probably the `options` [here](https://github.com/mixmaxhq/arena/blob/master/src/server/bull/index.js#L42) should be leveraged to allow carrying the prefix settings?

**Comment by randallm** [comment]
I agree, this should be fixed. I will take a look and add this feature in the coming days — if this is of high priority to you please consider submitting a pull request. :)
