### ISSUE TITLE
Disable express listen when using Arena as a module

### ISSUE THREAD

**Issue by kievechua** [mixmaxhq/arena#18]
It will be helpful if can disable it.
Else it will listen to 2 ports, 5000 & 4567

**Comment by randallm** [comment]
This feature has been added and will make its way to the next release. I will post in this thread when it is available.

**Comment by randallm** [comment]
@kievechua This is in the current (v1.4.1) release, with the [`disableListen` flag](https://github.com/mixmaxhq/arena/blob/6ec772af43a19306309954caf7d18da3da89c331/index.js).
